version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
      
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      # - aws-cli/setup:
      #     profile-name: circleci
      - run: |
              aws cloudformation create-stack --stack-name infra --template-body file://template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

workflows:
  say-hello-workflow:
    jobs:
      - create_infrastructure
