Parameters:
# Existing Bucket name
  PipelineID:
    Description: Existing Bucket name
    Type: String
Resources:
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website
  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          ## below are changes from udacity provided solutions
          - DomainName: !Sub "${PipelineID}.s3-website-us-west-2.amazonaws.com"
            Id: webpage
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all
Outputs:
  PipelineID:
    Value: !Sub ${PipelineID}
    Export:
      Name: PipelineID
  CDN:
    Value: !GetAtt WebpageCDN.Id
    Export:
      Name: CDN